name: "Vulnerability Scan on Docker Image"
description: "This uses Trivy to run a security scan on a docker image"

inputs:
  image-ref:
    description: Image reference
    required: true
  latest:
    description: Skip calling the setup-trivy action to install trivy
    default: "false"

runs:
  using: composite
  steps:
  - name: Run Trivy vulnerability scanner
    uses: aquasecurity/trivy-action@0.28.0
    with:
      image-ref: ${{ inputs.image-ref }}
      format: 'table' # Output format (table, json, template, sarif, cyclonedx, spdx, spdx-json, github, cosign-vuln)
      exit-code: '1'
      ignore-unfixed: true # Ignore unpatched/unfixed vulnerabilities
      vuln-type: 'os,library'
      severity: 'CRITICAL,HIGH' # UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
      skip-setup-trivy: ${{ inputs.skip-setup-trivy }}
